import os

with open(r'C:\Users\couvr\Documents\Projects\Trail Dust\2019_photo_album.html', 'w') as new_html_file:
    new_html_file.write('<!DOCTYPE html>\n<html>\n\t<head>\n\t\t<title>Trail Dust</title>\n\t\t<script src="https://code.jquery.com/jquery-1.10.2.js"></script>\n\t\t<script defer src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>\n\t\t<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>\n\t\t\n\t\t<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">\n\t\t<link rel="stylesheet" type="text/css" href="css/style.css">\n\t\t<link rel="stylesheet" type="text/css" href="css/next_year.css">\n\t</head>\n\t<body>\n\t\t<!-- Navigation bar-->\n\t\t<div id="nav-placeholder"></div>\n\n\t\t<script>\n\t\t$(function(){\n\t\t$("#nav-placeholder").load("./nav.html");\n\t\t});\n\t\t</script>\n\t\t<!--end of Navigation bar -->\n\n\t\t<!--Add Your Code below-->\n\n\t\t<br>')

    photos = os.listdir(r"C:\Users\couvr\Documents\Projects\Trail Dust\images\2019 Photo Album")
    for i in range(int(len(photos)/2)):
        new_html_file.write(f'\n\n\t\t<div class="row">\n\t\t\t<div class="col-md-2"></div>\n\t\t\t<div class="col-md-4">\n\t\t\t\t<div class="card border-0">\n\t\t\t\t\t<img src="images/2019 Photo Album/{photos[i*2]}">\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t\t<div class="col-md-4">\n\t\t\t\t<div class="card border-0">\n\t\t\t\t\t<img src="images/2019 Photo Album/{photos[i*2+1]}">\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t\t<div class="col-md-2"></div>\n\t\t</div>\n\t\t<br>')
    if len(photos)%2:
        new_html_file.write(f'\n\t\t<div class="row">\n\t\t\t<div class="col-md-2"></div>\n\t\t\t<div class="col-md-4">\n\t\t\t\t<div class="card border-0">\n\t\t\t\t\t<img src="images/2019 Photo Album/{photos[-1]}">\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t\t</div>')

    new_html_file.write('\t\t<!--Add Your Code above-->\n\n\t\t<br>\n\t\t<br>\n\n\t\t<!-- Footer -->\n\t\t<div id="footer-placeholder"></div>\n\n\t\t<script>\n\t\t\t$(function(){\n\t\t\t\t$("#footer-placeholder").load("./footer.html");\n\t\t\t});\n\t\t</script>\n\t\t<!-- Footer -->\n\n\t\t\n\n\t</body>\n</html>')